---
title: "In-class Exercise 8: Global and Local Spatial Autocorrelation "
execute: 
  message: true
  warning: false
  echo: true
  eval: true
date: "6 March 2023"
date-modified: "`r Sys.Date()`"
# number-sections: true
editor: visual
format: html
---

# 1 Overview

# 2 The Data

# 3 Getting Started
```{r}
# install corrplot manually
pacman::p_load(olsrr, readr, ggpubr, sf, spdep, GWmodel, tmap, tidyr, dyplr, tidyverse, gtsummary)
```

```{r}
mpsz = st_read(dsn = "data/geospatial", layer = "MP14_SUBZONE_WEB_PL") %>% st_transform(crs=3414)
```

```{r}
condo_resale = read_csv("data/aspatial/Condo_resale_2015.csv")
```

```{r}
dplyr::glimpse(condo_resale)
```

```{r}
summary(condo_resale)
```

```{r}
condo_resale.sf <- st_as_sf(condo_resale,
                            coords = c("LONGITUDE", "LATITUDE"),
                            crs=4326) %>%
  st_transform(crs=3414)
```

```{r}
condo_resale.sf <- condo_resale.sf %>%
  dplyr::mutate(`LOG_SELLING_PRICE` = log(SELLING_PRICE))
```

```{r}
condo.slr <- lm(formula=SELLING_PRICE ~ AREA_SQM, data = condo_resale.sf)
```

