<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Valencia">
<meta name="dcterms.date" content="2023-02-13">

<title>IS415-GAA - Take-home Exercise 2: Spatio-temporal Analysis of COVID-19 Vaccination Trends at the Sub-district Level, DKI Jakarta</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">IS415-GAA</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html">
 <span class="dropdown-text">Hands-on Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html">
 <span class="dropdown-text">Hands-on Exercise 6</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex02/In-class_Ex02.html">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03.html">
 <span class="dropdown-text">In-class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/In-class_Ex04.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex05/In-class_Ex05.html">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex06/In-class_Ex06.html">
 <span class="dropdown-text">In-class Exercise 6</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html">
 <span class="dropdown-text">Take-home Exercise 2</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#setting-the-scene" id="toc-setting-the-scene" class="nav-link active" data-scroll-target="#setting-the-scene">1 Setting the Scene</a></li>
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives">2 Objectives</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">3 The Data</a>
  <ul class="collapse">
  <li><a href="#aspatial-data" id="toc-aspatial-data" class="nav-link" data-scroll-target="#aspatial-data">3.1 Aspatial Data</a></li>
  <li><a href="#geospatial-data" id="toc-geospatial-data" class="nav-link" data-scroll-target="#geospatial-data">3.2 Geospatial Data</a></li>
  </ul></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started">4 Getting Started</a>
  <ul class="collapse">
  <li><a href="#installing-and-loading-r-packages" id="toc-installing-and-loading-r-packages" class="nav-link" data-scroll-target="#installing-and-loading-r-packages">4.1 Installing and Loading R packages</a></li>
  <li><a href="#data-wrangling-geospatial-data" id="toc-data-wrangling-geospatial-data" class="nav-link" data-scroll-target="#data-wrangling-geospatial-data">4.2 Data Wrangling: Geospatial Data</a>
  <ul class="collapse">
  <li><a href="#importing-the-geospatial-data" id="toc-importing-the-geospatial-data" class="nav-link" data-scroll-target="#importing-the-geospatial-data">4.2.1 Importing the Geospatial Data</a></li>
  <li><a href="#data-pre-processing" id="toc-data-pre-processing" class="nav-link" data-scroll-target="#data-pre-processing">4.2.2 Data Pre-Processing</a></li>
  <li><a href="#data-visualisation" id="toc-data-visualisation" class="nav-link" data-scroll-target="#data-visualisation">4.2.3 Data Visualisation</a></li>
  <li><a href="#retaining-relavant-columns-only" id="toc-retaining-relavant-columns-only" class="nav-link" data-scroll-target="#retaining-relavant-columns-only">4.2.4 Retaining relavant columns only</a></li>
  <li><a href="#renaming-the-columns-in-english" id="toc-renaming-the-columns-in-english" class="nav-link" data-scroll-target="#renaming-the-columns-in-english">4.2.5 Renaming the Columns in English</a></li>
  <li><a href="#brief-eda-of-geospatial-data" id="toc-brief-eda-of-geospatial-data" class="nav-link" data-scroll-target="#brief-eda-of-geospatial-data">4.2.6 Brief EDA of Geospatial Data</a></li>
  </ul></li>
  <li><a href="#data-wrangling-aspatial-data" id="toc-data-wrangling-aspatial-data" class="nav-link" data-scroll-target="#data-wrangling-aspatial-data">4.3 Data Wrangling: Aspatial Data</a>
  <ul class="collapse">
  <li><a href="#pre-importing-eda" id="toc-pre-importing-eda" class="nav-link" data-scroll-target="#pre-importing-eda">4.3.1 Pre-Importing EDA</a></li>
  <li><a href="#creating-an-aspatial-data-pre-processing-function" id="toc-creating-an-aspatial-data-pre-processing-function" class="nav-link" data-scroll-target="#creating-an-aspatial-data-pre-processing-function">4.3.2 Creating an Aspatial Data Pre-processing Function</a></li>
  <li><a href="#importing-the-aspatial-data" id="toc-importing-the-aspatial-data" class="nav-link" data-scroll-target="#importing-the-aspatial-data">Importing the Aspatial Data</a></li>
  </ul></li>
  <li><a href="#choropleth-mapping-and-analysis" id="toc-choropleth-mapping-and-analysis" class="nav-link" data-scroll-target="#choropleth-mapping-and-analysis">4.3 Choropleth Mapping and Analysis</a></li>
  <li><a href="#local-gi-analysis" id="toc-local-gi-analysis" class="nav-link" data-scroll-target="#local-gi-analysis">4.4 Local Gi* Analysis</a></li>
  <li><a href="#emerging-hot-spot-analysis-ehsa" id="toc-emerging-hot-spot-analysis-ehsa" class="nav-link" data-scroll-target="#emerging-hot-spot-analysis-ehsa">4.5 Emerging Hot Spot Analysis (EHSA)</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">5 References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 2: Spatio-temporal Analysis of COVID-19 Vaccination Trends at the Sub-district Level, DKI Jakarta</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Valencia </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 13, 2023</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">February 16, 2023</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="setting-the-scene" class="level1">
<h1>1 Setting the Scene</h1>
<p>Since late December 2019, an outbreak of a novel coronavirus disease (COVID-19; previously known as 2019-nCoV) was reported in Wuhan, China, which had subsequently affected 210 countries worldwide. In general, COVID-19 is an acute resolved disease but it can also be deadly, with a 2% case fatality rate.</p>
<p>The COVID-19 vaccination in Indonesia is an ongoing mass immunisation in response to the COVID-19 pandemic in Indonesia. On 13 January 2021, the program commenced when President Joko Widodo was vaccinated at the presidential palace. In terms of total doses given, Indonesia ranks third in Asia and fifth in the world.</p>
<p>According to wikipedia, as of 5 February 2023 at 18:00 WIB (UTC+7), 204,266,655 people had received the first dose of the vaccine and 175,131,893 people had been fully vaccinated; 69,597,474 of them had been inoculated with the booster or the third dose, while 1,585,164 had received the fourth dose. Jakarta has the highest percentage of population fully vaccinated with 103.46%, followed by Bali and Special Region of Yogyakarta with 85.45% and 83.02% respectively.</p>
<p>Despite its compactness, the cumulative vaccination rate are not evenly distributed within DKI Jakarta. The question is where are the sub-districts with relatively higher number of vaccination rate and how they changed over time.</p>
</section>
<section id="objectives" class="level1">
<h1>2 Objectives</h1>
<p>Exploratory Spatial Data Analysis (ESDA) hold tremendous potential to address complex problems facing society. In this study, you are tasked to apply appropriate Local Indicators of Spatial Association (LISA) and Emerging Hot Spot Analysis (EHSA) to undercover the spatio-temporal trends of COVID-19 vaccination in DKI Jakarta.</p>
</section>
<section id="the-data" class="level1">
<h1>3 The Data</h1>
<section id="aspatial-data" class="level2">
<h2 class="anchored" data-anchor-id="aspatial-data">3.1 Aspatial Data</h2>
<p>For the purpose of this assignment, data from <a href="https://riwayat-file-vaksinasi-dki-jakarta-jakartagis.hub.arcgis.com/">Riwayat File Vaksinasi DKI Jakarta</a> will be used. Daily vaccination data are provides. You are only required to download either the first day of the month or last day of the month of the study period.</p>
</section>
<section id="geospatial-data" class="level2">
<h2 class="anchored" data-anchor-id="geospatial-data">3.2 Geospatial Data</h2>
<p>For the purpose of this study, DKI Jakarta administration boundary 2019 will be used. The data set can be downloaded at Indonesia Geospatial portal, specifically at <a href="https://www.indonesia-geospasial.com/2020/04/download-shapefile-shp-batas-desa.html">this page</a>.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>The national Projected Coordinates Systems of Indonesia is DGN95 / Indonesia TM-3 zone 54.1.</li>
<li>Exclude all the outer islands from the DKI Jakarta sf data frame, and</li>
<li>Retain the first nine fields in the DKI Jakarta sf data frame. The ninth field JUMLAH_PEN = Total Population.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="getting-started" class="level1">
<h1>4 Getting Started</h1>
<section id="installing-and-loading-r-packages" class="level2">
<h2 class="anchored" data-anchor-id="installing-and-loading-r-packages">4.1 Installing and Loading R packages</h2>
<ul>
<li><p><a href="https://r-spatial.github.io/sf/">sf</a>: to import, manage, and process geospatial data</p></li>
<li><p><a href="https://www.tidyverse.org/">tidyverse</a>: a collection of packages (<a href="https://readr.tidyverse.org/">readr</a> for importing delimited text file, <a href="https://tidyr.tidyverse.org/">tidyr</a> for tidying data, <a href="https://dplyr.tidyverse.org/">dplyr</a> for wrangling data)</p></li>
<li><p><a href="https://cran.r-project.org/web/packages/tmap/">tmap</a>: provides functions for plotting cartographic quality static point patterns maps or interactive maps</p></li>
<li><p><a href="https://cran.r-project.org/web/packages/sfdep/">sfdep</a>: for spatial dependence of simple features</p></li>
<li><p><a href="https://readxl.tidyverse.org/reference/read_excel.html">readxl</a>: for importing Excel worksheets(.xlsx)</p></li>
<li><p><a href="https://cran.r-project.org/package=plyr">plyr</a>: for splitting data, applying functions and combining results</p></li>
</ul>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, sfdep, readxl, plyr, tmap, tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="data-wrangling-geospatial-data" class="level2">
<h2 class="anchored" data-anchor-id="data-wrangling-geospatial-data">4.2 Data Wrangling: Geospatial Data</h2>
<section id="importing-the-geospatial-data" class="level3">
<h3 class="anchored" data-anchor-id="importing-the-geospatial-data">4.2.1 Importing the Geospatial Data</h3>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bd stands for "batas desa", translated as "village boundary"</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># reads in geospatial data and stores into bd_jakarta dataframe</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>bd_jakarta <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">layer =</span> <span class="st">"BATAS_DESA_DESEMBER_2019_DUKCAPIL_DKI_JAKARTA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `BATAS_DESA_DESEMBER_2019_DUKCAPIL_DKI_JAKARTA' from data source 
  `C:\valtyl\IS415-GAA\Take-home_Ex\Take-home_Ex02\data\geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 269 features and 161 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 106.3831 ymin: -6.370815 xmax: 106.9728 ymax: -5.184322
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<p>From the output message, we learn that: - Geometry type: Multipolygon - 269 features, 161 fields - Assigned CRS is <a href="https://epsg.io/4326">WGS 84</a>, ‘World Geodetic System 1984’ (This is not appropriate as this geospatial dataset is Indonesian-specific hence we will have to use the national CRS of Indonesia, <a href="https://epsg.io/23845">DGN 95</a>, ‘Datum Geodesi Nasional 1995’. We will change this later on.) (Refer to note in section 3.2)</p>
</section>
<section id="data-pre-processing" class="level3">
<h3 class="anchored" data-anchor-id="data-pre-processing">4.2.2 Data Pre-Processing</h3>
<p>Before visualising our data, we need to check if there are: - invalid geometries - or missing values These can impact future calculations and representations</p>
<section id="invalid-geometries" class="level4">
<h4 class="anchored" data-anchor-id="invalid-geometries">4.2.2.1 Invalid Geometries</h4>
<p>Checking for invalid geometries:</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># function breakdown:</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the st_is_valid function checks whether a geometry is valid</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># which returns the indices of certain values based on logical conditions</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># length returns the length of data objects</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># checks for the number of geometries that are NOT valid</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(<span class="fu">st_is_valid</span>(bd_jakarta) <span class="sc">==</span> <span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>The message output shows that there are no invalid geometries.</p>
</section>
<section id="missing-values" class="level4">
<h4 class="anchored" data-anchor-id="missing-values">4.2.2.2 Missing Values</h4>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the rowSums(is.na(bd_jakarta))!=0 checks every row if there are NA values, returning TRUE or FALSE</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the bd_jakarta 'wrapper' prints said rows that contain NA values</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>bd_jakarta[<span class="fu">rowSums</span>(<span class="fu">is.na</span>(bd_jakarta))<span class="sc">!=</span><span class="dv">0</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 2 features and 161 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 106.8412 ymin: -6.154036 xmax: 106.8612 ymax: -6.144973
Geodetic CRS:  WGS 84
    OBJECT_ID KODE_DESA             DESA   KODE    PROVINSI KAB_KOTA KECAMATAN
243     25645  31888888     DANAU SUNTER 318888 DKI JAKARTA     &lt;NA&gt;      &lt;NA&gt;
244     25646  31888888 DANAU SUNTER DLL 318888 DKI JAKARTA     &lt;NA&gt;      &lt;NA&gt;
    DESA_KELUR JUMLAH_PEN JUMLAH_KK LUAS_WILAY KEPADATAN PERPINDAHA JUMLAH_MEN
243       &lt;NA&gt;          0         0          0         0          0          0
244       &lt;NA&gt;          0         0          0         0          0          0
    PERUBAHAN WAJIB_KTP SILAM KRISTEN KHATOLIK HINDU BUDHA KONGHUCU KEPERCAYAA
243         0         0     0       0        0     0     0        0          0
244         0         0     0       0        0     0     0        0          0
    PRIA WANITA BELUM_KAWI KAWIN CERAI_HIDU CERAI_MATI U0 U5 U10 U15 U20 U25
243    0      0          0     0          0          0  0  0   0   0   0   0
244    0      0          0     0          0          0  0  0   0   0   0   0
    U30 U35 U40 U45 U50 U55 U60 U65 U70 U75 TIDAK_BELU BELUM_TAMA TAMAT_SD SLTP
243   0   0   0   0   0   0   0   0   0   0          0          0        0    0
244   0   0   0   0   0   0   0   0   0   0          0          0        0    0
    SLTA DIPLOMA_I DIPLOMA_II DIPLOMA_IV STRATA_II STRATA_III BELUM_TIDA
243    0         0          0          0         0          0          0
244    0         0          0          0         0          0          0
    APARATUR_P TENAGA_PEN WIRASWASTA PERTANIAN NELAYAN AGAMA_DAN PELAJAR_MA
243          0          0          0         0       0         0          0
244          0          0          0         0       0         0          0
    TENAGA_KES PENSIUNAN LAINNYA GENERATED KODE_DES_1 BELUM_ MENGUR_ PELAJAR_
243          0         0       0      &lt;NA&gt;       &lt;NA&gt;      0       0        0
244          0         0       0      &lt;NA&gt;       &lt;NA&gt;      0       0        0
    PENSIUNA_1 PEGAWAI_ TENTARA KEPOLISIAN PERDAG_ PETANI PETERN_ NELAYAN_1
243          0        0       0          0       0      0       0         0
244          0        0       0          0       0      0       0         0
    INDUSTR_ KONSTR_ TRANSP_ KARYAW_ KARYAW1 KARYAW1_1 KARYAW1_12 BURUH BURUH_
243        0       0       0       0       0         0          0     0      0
244        0       0       0       0       0         0          0     0      0
    BURUH1 BURUH1_1 PEMBANT_ TUKANG TUKANG_1 TUKANG_12 TUKANG__13 TUKANG__14
243      0        0        0      0        0         0          0          0
244      0        0        0      0        0         0          0          0
    TUKANG__15 TUKANG__16 TUKANG__17 PENATA PENATA_ PENATA1_1 MEKANIK SENIMAN_
243          0          0          0      0       0         0       0        0
244          0          0          0      0       0         0       0        0
    TABIB PARAJI_ PERANCA_ PENTER_ IMAM_M PENDETA PASTOR WARTAWAN USTADZ JURU_M
243     0       0        0       0      0       0      0        0      0      0
244     0       0        0       0      0       0      0        0      0      0
    PROMOT ANGGOTA_ ANGGOTA1 ANGGOTA1_1 PRESIDEN WAKIL_PRES ANGGOTA1_2
243      0        0        0          0        0          0          0
244      0        0        0          0        0          0          0
    ANGGOTA1_3 DUTA_B GUBERNUR WAKIL_GUBE BUPATI WAKIL_BUPA WALIKOTA WAKIL_WALI
243          0      0        0          0      0          0        0          0
244          0      0        0          0      0          0        0          0
    ANGGOTA1_4 ANGGOTA1_5 DOSEN GURU PILOT PENGACARA_ NOTARIS ARSITEK AKUNTA_
243          0          0     0    0     0          0       0       0       0
244          0          0     0    0     0          0       0       0       0
    KONSUL_ DOKTER BIDAN PERAWAT APOTEK_ PSIKIATER PENYIA_ PENYIA1 PELAUT
243       0      0     0       0       0         0       0       0      0
244       0      0     0       0       0         0       0       0      0
    PENELITI SOPIR PIALAN PARANORMAL PEDAGA_ PERANG_ KEPALA_ BIARAW_ WIRASWAST_
243        0     0      0          0       0       0       0       0          0
244        0     0      0          0       0       0       0       0          0
    LAINNYA_12 LUAS_DESA KODE_DES_3 DESA_KEL_1 KODE_12
243          0         0       &lt;NA&gt;       &lt;NA&gt;       0
244          0         0       &lt;NA&gt;       &lt;NA&gt;       0
                          geometry
243 MULTIPOLYGON (((106.8612 -6...
244 MULTIPOLYGON (((106.8504 -6...</code></pre>
</div>
</div>
<p>The message output shows that there are 2 rows with missing values for the columns <code>KAB_KOTA</code> (City), <code>KECAMATAN</code> (District), <code>DESA_KELUR</code> (Village) and a few more others. We can also see that there are way too many columns, and we will remove the unnecessary columns later on.</p>
<p>To clean up, we will remove the rows that have NA values in <code>DESA_KELUR</code> since we are interested in the dataset on a sub-district level:</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># removes rows that have an NA value in DESA_KELUR</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># in context of this data, we can use other columns, such as KAB_KOTA or KECAMATAN</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># but since we're looking at this on a sub-district level, DESA_KELUR seemed most appropriate</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>bd_jakarta <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(bd_jakarta,<span class="fu">c</span>(<span class="st">"DESA_KELUR"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="verifying-transforming-the-coordinate-system" class="level4">
<h4 class="anchored" data-anchor-id="verifying-transforming-the-coordinate-system">4.2.2.3 Verifying &amp; Transforming the Coordinate System</h4>
<p>Checking the CRS of <code>bd_jakarta</code>:</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># retrieves the coordinate system of bd_jakarta</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(bd_jakarta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: WGS 84 
  wkt:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]</code></pre>
</div>
</div>
<p>As mentioned in section 4.2.1, WGS 84 is not appropriate and we should change it to DGN 95:</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># transforms the CRS to DGN95, ESPG code 23845</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>bd_jakarta <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(bd_jakarta, <span class="dv">23845</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Checking if the CRS has been properly assigned:</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(bd_jakarta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:23845 
  wkt:
PROJCRS["DGN95 / Indonesia TM-3 zone 54.1",
    BASEGEOGCRS["DGN95",
        DATUM["Datum Geodesi Nasional 1995",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4755]],
    CONVERSION["Indonesia TM-3 zone 54.1",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",139.5,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9999,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",200000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",1500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting (X)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing (Y)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Cadastre."],
        AREA["Indonesia - onshore east of 138°E."],
        BBOX[-9.19,138,-1.49,141.01]],
    ID["EPSG",23845]]</code></pre>
</div>
</div>
<p>The transformation is done.</p>
</section>
</section>
<section id="data-visualisation" class="level3">
<h3 class="anchored" data-anchor-id="data-visualisation">4.2.3 Data Visualisation</h3>
<p>First, we will visualise the geometry of Jakarta:</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(bd_jakarta))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the output, it shows that <code>bd_jakarta</code> includes the main land but also many other outer islands that we are not relevant to our analysis in this assignment. (Refer to note in section 3.2)</p>
<p>To remove the outer islands, we should look at how unique values at the City level, <code>KAB_KOTA</code>:</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># outputs unique values of the KAB_KOTA field</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(bd_jakarta<span class="sc">$</span><span class="st">"KAB_KOTA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "JAKARTA BARAT"    "JAKARTA PUSAT"    "KEPULAUAN SERIBU" "JAKARTA UTARA"   
[5] "JAKARTA TIMUR"    "JAKARTA SELATAN" </code></pre>
</div>
</div>
<p>From the output, the cities within Jakarta have a JAKARTA prefix, while KEPULAUAN SERIBU (which means ‘Thousand Islands’) refers to the outer islands. Visualising <code>KAB_KOTA</code> will confirm this:</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># with bd_jakarta as the input data (setting the 'base')</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># draw the KAB_KOTA (city) polygons</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># essentially shades the map according to the city divisions</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(bd_jakarta) <span class="sc">+</span> </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"KAB_KOTA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The above visualisation proves that KEPULAUAN SERIBU are the outer islands to remove:</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># filters out the outer islands by accepting only if the value of KAB_KOTA is NOT KEPULAUAN SERIBU</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>bd_jakarta <span class="ot">&lt;-</span> <span class="fu">filter</span>(bd_jakarta, KAB_KOTA <span class="sc">!=</span> <span class="st">"KEPULAUAN SERIBU"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="retaining-relavant-columns-only" class="level3">
<h3 class="anchored" data-anchor-id="retaining-relavant-columns-only">4.2.4 Retaining relavant columns only</h3>
<p>As seen in section 4.2.2.2, there were many unnecessary and irrelevant columns that we could remove. (Refer to note in section 3.2)</p>
<p>Retaining the relevant fields (first 9 fields) to our analysis:</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># filters out other fields by accepting only the first 9 fields</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>bd_jakarta <span class="ot">&lt;-</span> bd_jakarta[, <span class="dv">0</span><span class="sc">:</span><span class="dv">9</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="renaming-the-columns-in-english" class="level3">
<h3 class="anchored" data-anchor-id="renaming-the-columns-in-english">4.2.5 Renaming the Columns in English</h3>
<p>For ease of comprehension:</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># with reference to: https://www.codegrepper.com/code-examples/r/rename+column+name+in+r</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># renames the columns in the style New_Name = OLD_NAME</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>bd_jakarta <span class="ot">&lt;-</span> bd_jakarta <span class="sc">%&gt;%</span> </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">rename</span>(</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Object_ID=</span>OBJECT_ID,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Province=</span>PROVINSI, </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">City=</span>KAB_KOTA, </span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">District=</span>KECAMATAN, </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Village_Code=</span>KODE_DESA, </span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Village=</span>DESA, </span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">Sub_District=</span>DESA_KELUR,</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">Code=</span>KODE, </span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">Total_Population=</span>JUMLAH_PEN</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="brief-eda-of-geospatial-data" class="level3">
<h3 class="anchored" data-anchor-id="brief-eda-of-geospatial-data">4.2.6 Brief EDA of Geospatial Data</h3>
<p>Summary of <code>bd_jakarta</code>:</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># reveals the data type of all fields + some values</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(bd_jakarta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 261
Columns: 10
$ Object_ID        &lt;dbl&gt; 25477, 25478, 25397, 25400, 25390, 25391, 25394, 2538…
$ Village_Code     &lt;chr&gt; "3173031006", "3173031007", "3171031003", "3171031006…
$ Village          &lt;chr&gt; "KEAGUNGAN", "GLODOK", "HARAPAN MULIA", "CEMPAKA BARU…
$ Code             &lt;dbl&gt; 317303, 317303, 317103, 317103, 317102, 317102, 31710…
$ Province         &lt;chr&gt; "DKI JAKARTA", "DKI JAKARTA", "DKI JAKARTA", "DKI JAK…
$ City             &lt;chr&gt; "JAKARTA BARAT", "JAKARTA BARAT", "JAKARTA PUSAT", "J…
$ District         &lt;chr&gt; "TAMAN SARI", "TAMAN SARI", "KEMAYORAN", "KEMAYORAN",…
$ Sub_District     &lt;chr&gt; "KEAGUNGAN", "GLODOK", "HARAPAN MULIA", "CEMPAKA BARU…
$ Total_Population &lt;dbl&gt; 21609, 9069, 29085, 41913, 15793, 33383, 35906, 21828…
$ geometry         &lt;MULTIPOLYGON [m]&gt; MULTIPOLYGON (((-3626874 69..., MULTIPOL…</code></pre>
</div>
</div>
<p>Number of unique sub-districts:</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(bd_jakarta<span class="sc">$</span><span class="st">"Sub_District"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 261</code></pre>
</div>
</div>
<p>Number of unique districts:</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(bd_jakarta<span class="sc">$</span><span class="st">"District"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 42</code></pre>
</div>
</div>
<p>Number of unique cities:</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(bd_jakarta<span class="sc">$</span><span class="st">"City"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
</div>
<p>There are 261 unique sub-districts, 42 unique districts and 5 unique cities. The maximum number of categories for mapping with tmap is 30. Even though max.categories can be adjusted in tmap_options, too many segmented sections on a single map will not provide much insights hence we should do the EDA at ‘City’ level:</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># shades the map according to the city divisions</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(bd_jakarta) <span class="sc">+</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"City"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex02_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="data-wrangling-aspatial-data" class="level2">
<h2 class="anchored" data-anchor-id="data-wrangling-aspatial-data">4.3 Data Wrangling: Aspatial Data</h2>
<section id="pre-importing-eda" class="level3">
<h3 class="anchored" data-anchor-id="pre-importing-eda">4.3.1 Pre-Importing EDA</h3>
<p>For the aspatial data, I have decided to download the data for last day of every month from July 2021 to June 2022. However, the last day of Feb 2022 provided on the website in section 3.1 is 27 Feb instead of 28 Feb.&nbsp;</p>
<p>This section is to check for any discrepancies in each .xlsx file in the ‘data/aspatial’ folder by performing EDA:</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>jul2021 <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/aspatial/Data Vaksinasi Berbasis Kelurahan (31 Juli 2021).xlsx"</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(jul2021)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 268
Columns: 27
$ `KODE KELURAHAN`                             &lt;chr&gt; NA, "3172051003", "317304…
$ `WILAYAH KOTA`                               &lt;chr&gt; NA, "JAKARTA UTARA", "JAK…
$ KECAMATAN                                    &lt;chr&gt; NA, "PADEMANGAN", "TAMBOR…
$ KELURAHAN                                    &lt;chr&gt; "TOTAL", "ANCOL", "ANGKE"…
$ SASARAN                                      &lt;dbl&gt; 8941211, 23947, 29381, 29…
$ `BELUM VAKSIN`                               &lt;dbl&gt; 4441501, 12333, 13875, 18…
$ `JUMLAH\r\nDOSIS 1`                          &lt;dbl&gt; 4499710, 11614, 15506, 10…
$ `JUMLAH\r\nDOSIS 2`                          &lt;dbl&gt; 1663218, 4181, 4798, 3658…
$ `TOTAL VAKSIN\r\nDIBERIKAN`                  &lt;dbl&gt; 6162928, 15795, 20304, 14…
$ `LANSIA\r\nDOSIS 1`                          &lt;dbl&gt; 502579, 1230, 2012, 865, …
$ `LANSIA\r\nDOSIS 2`                          &lt;dbl&gt; 440910, 1069, 1729, 701, …
$ `LANSIA TOTAL \r\nVAKSIN DIBERIKAN`          &lt;dbl&gt; 943489, 2299, 3741, 1566,…
$ `PELAYAN PUBLIK\r\nDOSIS 1`                  &lt;dbl&gt; 1052883, 3333, 2586, 2837…
$ `PELAYAN PUBLIK\r\nDOSIS 2`                  &lt;dbl&gt; 666009, 2158, 1374, 1761,…
$ `PELAYAN PUBLIK TOTAL\r\nVAKSIN DIBERIKAN`   &lt;dbl&gt; 1718892, 5491, 3960, 4598…
$ `GOTONG ROYONG\r\nDOSIS 1`                   &lt;dbl&gt; 56660, 78, 122, 174, 71, …
$ `GOTONG ROYONG\r\nDOSIS 2`                   &lt;dbl&gt; 38496, 51, 84, 106, 57, 7…
$ `GOTONG ROYONG TOTAL\r\nVAKSIN DIBERIKAN`    &lt;dbl&gt; 95156, 129, 206, 280, 128…
$ `TENAGA KESEHATAN\r\nDOSIS 1`                &lt;dbl&gt; 76397, 101, 90, 215, 73, …
$ `TENAGA KESEHATAN\r\nDOSIS 2`                &lt;dbl&gt; 67484, 91, 82, 192, 67, 3…
$ `TENAGA KESEHATAN TOTAL\r\nVAKSIN DIBERIKAN` &lt;dbl&gt; 143881, 192, 172, 407, 14…
$ `TAHAPAN 3\r\nDOSIS 1`                       &lt;dbl&gt; 2279398, 5506, 9012, 5408…
$ `TAHAPAN 3\r\nDOSIS 2`                       &lt;dbl&gt; 446028, 789, 1519, 897, 4…
$ `TAHAPAN 3 TOTAL\r\nVAKSIN DIBERIKAN`        &lt;dbl&gt; 2725426, 6295, 10531, 630…
$ `REMAJA\r\nDOSIS 1`                          &lt;dbl&gt; 531793, 1366, 1684, 1261,…
$ `REMAJA\r\nDOSIS 2`                          &lt;dbl&gt; 4291, 23, 10, 1, 1, 8, 6,…
$ `REMAJA TOTAL\r\nVAKSIN DIBERIKAN`           &lt;dbl&gt; 536084, 1389, 1694, 1262,…</code></pre>
</div>
</div>
<p>The above output shows that there are no duplicates for the columns.</p>
<p>Below, similar codes were used to check for the other excel files. There are no duplicates in the rest of the files. But, the excel files for July 2021 to February 2022 have 27 columns while those for March 2022 to June 2022 have 34 columns.</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>aug2021 <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/aspatial/Data Vaksinasi Berbasis Kelurahan (31 Agustus 2021).xlsx"</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(aug2021)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 268
Columns: 27
$ `KODE KELURAHAN`                             &lt;chr&gt; NA, "3172051003", "317304…
$ `WILAYAH KOTA`                               &lt;chr&gt; NA, "JAKARTA UTARA", "JAK…
$ KECAMATAN                                    &lt;chr&gt; NA, "PADEMANGAN", "TAMBOR…
$ KELURAHAN                                    &lt;chr&gt; "TOTAL", "ANCOL", "ANGKE"…
$ SASARAN                                      &lt;dbl&gt; 8941211, 23947, 29381, 29…
$ `BELUM VAKSIN`                               &lt;dbl&gt; 3277484, 9191, 10400, 125…
$ `JUMLAH\r\nDOSIS 1`                          &lt;dbl&gt; 5663727, 14756, 18981, 16…
$ `JUMLAH\r\nDOSIS 2`                          &lt;dbl&gt; 3412906, 8935, 10470, 776…
$ `TOTAL VAKSIN\r\nDIBERIKAN`                  &lt;dbl&gt; 9076633, 23691, 29451, 24…
$ `LANSIA\r\nDOSIS 1`                          &lt;dbl&gt; 535001, 1300, 2104, 1043,…
$ `LANSIA\r\nDOSIS 2`                          &lt;dbl&gt; 468678, 1140, 1849, 780, …
$ `LANSIA TOTAL \r\nVAKSIN DIBERIKAN`          &lt;dbl&gt; 1003679, 2440, 3953, 1823…
$ `PELAYAN PUBLIK\r\nDOSIS 1`                  &lt;dbl&gt; 1393352, 4194, 3643, 4293…
$ `PELAYAN PUBLIK\r\nDOSIS 2`                  &lt;dbl&gt; 1007921, 3135, 2519, 2548…
$ `PELAYAN PUBLIK TOTAL\r\nVAKSIN DIBERIKAN`   &lt;dbl&gt; 2401273, 7329, 6162, 6841…
$ `GOTONG ROYONG\r\nDOSIS 1`                   &lt;dbl&gt; 65340, 89, 137, 188, 80, …
$ `GOTONG ROYONG\r\nDOSIS 2`                   &lt;dbl&gt; 53995, 77, 119, 163, 71, …
$ `GOTONG ROYONG TOTAL\r\nVAKSIN DIBERIKAN`    &lt;dbl&gt; 119335, 166, 256, 351, 15…
$ `TENAGA KESEHATAN\r\nDOSIS 1`                &lt;dbl&gt; 79502, 106, 92, 229, 78, …
$ `TENAGA KESEHATAN\r\nDOSIS 2`                &lt;dbl&gt; 72588, 96, 83, 203, 74, 3…
$ `TENAGA KESEHATAN TOTAL\r\nVAKSIN DIBERIKAN` &lt;dbl&gt; 152090, 202, 175, 432, 15…
$ `TAHAPAN 3\r\nDOSIS 1`                       &lt;dbl&gt; 2941837, 7385, 11033, 872…
$ `TAHAPAN 3\r\nDOSIS 2`                       &lt;dbl&gt; 1377349, 3277, 4541, 3010…
$ `TAHAPAN 3 TOTAL\r\nVAKSIN DIBERIKAN`        &lt;dbl&gt; 4319186, 10662, 15574, 11…
$ `REMAJA\r\nDOSIS 1`                          &lt;dbl&gt; 648695, 1682, 1972, 2090,…
$ `REMAJA\r\nDOSIS 2`                          &lt;dbl&gt; 432375, 1210, 1359, 1062,…
$ `REMAJA TOTAL\r\nVAKSIN DIBERIKAN`           &lt;dbl&gt; 1081070, 2892, 3331, 3152…</code></pre>
</div>
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>sep2021 <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/aspatial/Data Vaksinasi Berbasis Kelurahan (30 September 2021).xlsx"</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(sep2021)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 268
Columns: 27
$ `KODE KELURAHAN`                             &lt;chr&gt; NA, "3172051003", "317304…
$ `WILAYAH KOTA`                               &lt;chr&gt; NA, "JAKARTA UTARA", "JAK…
$ KECAMATAN                                    &lt;chr&gt; NA, "PADEMANGAN", "TAMBOR…
$ KELURAHAN                                    &lt;chr&gt; "TOTAL", "ANCOL", "ANGKE"…
$ SASARAN                                      &lt;dbl&gt; 8941211, 23947, 29381, 29…
$ `BELUM VAKSIN`                               &lt;dbl&gt; 2235772, 6688, 7581, 8708…
$ `JUMLAH\r\nDOSIS 1`                          &lt;dbl&gt; 6705439, 17259, 21800, 20…
$ `JUMLAH\r\nDOSIS 2`                          &lt;dbl&gt; 5171697, 13376, 16438, 14…
$ `TOTAL VAKSIN\r\nDIBERIKAN`                  &lt;dbl&gt; 11877136, 30635, 38238, 3…
$ `LANSIA\r\nDOSIS 1`                          &lt;dbl&gt; 587215, 1417, 2270, 1263,…
$ `LANSIA\r\nDOSIS 2`                          &lt;dbl&gt; 518944, 1263, 2033, 988, …
$ `LANSIA TOTAL \r\nVAKSIN DIBERIKAN`          &lt;dbl&gt; 1106159, 2680, 4303, 2251…
$ `PELAYAN PUBLIK\r\nDOSIS 1`                  &lt;dbl&gt; 1468382, 3938, 3883, 4540…
$ `PELAYAN PUBLIK\r\nDOSIS 2`                  &lt;dbl&gt; 1305200, 3454, 3356, 3903…
$ `PELAYAN PUBLIK TOTAL\r\nVAKSIN DIBERIKAN`   &lt;dbl&gt; 2773582, 7392, 7239, 8443…
$ `GOTONG ROYONG\r\nDOSIS 1`                   &lt;dbl&gt; 84049, 158, 173, 248, 100…
$ `GOTONG ROYONG\r\nDOSIS 2`                   &lt;dbl&gt; 75657, 148, 157, 229, 91,…
$ `GOTONG ROYONG TOTAL\r\nVAKSIN DIBERIKAN`    &lt;dbl&gt; 159706, 306, 330, 477, 19…
$ `TENAGA KESEHATAN\r\nDOSIS 1`                &lt;dbl&gt; 112296, 140, 135, 329, 11…
$ `TENAGA KESEHATAN\r\nDOSIS 2`                &lt;dbl&gt; 104381, 124, 125, 300, 11…
$ `TENAGA KESEHATAN TOTAL\r\nVAKSIN DIBERIKAN` &lt;dbl&gt; 216677, 264, 260, 629, 23…
$ `TAHAPAN 3\r\nDOSIS 1`                       &lt;dbl&gt; 3677943, 9564, 12969, 114…
$ `TAHAPAN 3\r\nDOSIS 2`                       &lt;dbl&gt; 2548057, 6788, 8944, 7023…
$ `TAHAPAN 3 TOTAL\r\nVAKSIN DIBERIKAN`        &lt;dbl&gt; 6226000, 16352, 21913, 18…
$ `REMAJA\r\nDOSIS 1`                          &lt;dbl&gt; 775554, 2042, 2370, 2510,…
$ `REMAJA\r\nDOSIS 2`                          &lt;dbl&gt; 619458, 1599, 1823, 1969,…
$ `REMAJA TOTAL\r\nVAKSIN DIBERIKAN`           &lt;dbl&gt; 1395012, 3641, 4193, 4479…</code></pre>
</div>
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>oct2021 <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/aspatial/Data Vaksinasi Berbasis Kelurahan (31 Oktober 2021).xlsx"</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(oct2021)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 268
Columns: 27
$ `KODE KELURAHAN`                             &lt;chr&gt; NA, "3172051003", "317304…
$ `WILAYAH KOTA`                               &lt;chr&gt; NA, "JAKARTA UTARA", "JAK…
$ KECAMATAN                                    &lt;chr&gt; NA, "PADEMANGAN", "TAMBOR…
$ KELURAHAN                                    &lt;chr&gt; "TOTAL", "ANCOL", "ANGKE"…
$ SASARAN                                      &lt;dbl&gt; 8941211, 23947, 29381, 29…
$ `BELUM VAKSIN`                               &lt;dbl&gt; 1880524, 5991, 6557, 7586…
$ `JUMLAH\r\nDOSIS 1`                          &lt;dbl&gt; 7060687, 17956, 22824, 21…
$ `JUMLAH\r\nDOSIS 2`                          &lt;dbl&gt; 5729001, 14504, 18185, 16…
$ `TOTAL VAKSIN\r\nDIBERIKAN`                  &lt;dbl&gt; 12789688, 32460, 41009, 3…
$ `LANSIA\r\nDOSIS 1`                          &lt;dbl&gt; 608940, 1447, 2336, 1322,…
$ `LANSIA\r\nDOSIS 2`                          &lt;dbl&gt; 543483, 1296, 2104, 1104,…
$ `LANSIA TOTAL \r\nVAKSIN DIBERIKAN`          &lt;dbl&gt; 1152423, 2743, 4440, 2426…
$ `PELAYAN PUBLIK\r\nDOSIS 1`                  &lt;dbl&gt; 1484292, 3972, 3917, 4595…
$ `PELAYAN PUBLIK\r\nDOSIS 2`                  &lt;dbl&gt; 1349105, 3555, 3465, 4072…
$ `PELAYAN PUBLIK TOTAL\r\nVAKSIN DIBERIKAN`   &lt;dbl&gt; 2833397, 7527, 7382, 8667…
$ `GOTONG ROYONG\r\nDOSIS 1`                   &lt;dbl&gt; 86323, 165, 175, 259, 101…
$ `GOTONG ROYONG\r\nDOSIS 2`                   &lt;dbl&gt; 81721, 160, 168, 245, 96,…
$ `GOTONG ROYONG TOTAL\r\nVAKSIN DIBERIKAN`    &lt;dbl&gt; 168044, 325, 343, 504, 19…
$ `TENAGA KESEHATAN\r\nDOSIS 1`                &lt;dbl&gt; 113911, 140, 136, 338, 12…
$ `TENAGA KESEHATAN\r\nDOSIS 2`                &lt;dbl&gt; 107383, 128, 128, 310, 12…
$ `TENAGA KESEHATAN TOTAL\r\nVAKSIN DIBERIKAN` &lt;dbl&gt; 221294, 268, 264, 648, 24…
$ `TAHAPAN 3\r\nDOSIS 1`                       &lt;dbl&gt; 3948804, 10101, 13744, 12…
$ `TAHAPAN 3\r\nDOSIS 2`                       &lt;dbl&gt; 2949023, 7567, 10266, 849…
$ `TAHAPAN 3 TOTAL\r\nVAKSIN DIBERIKAN`        &lt;dbl&gt; 6897827, 17668, 24010, 20…
$ `REMAJA\r\nDOSIS 1`                          &lt;dbl&gt; 818417, 2131, 2516, 2672,…
$ `REMAJA\r\nDOSIS 2`                          &lt;dbl&gt; 698286, 1798, 2054, 2220,…
$ `REMAJA TOTAL\r\nVAKSIN DIBERIKAN`           &lt;dbl&gt; 1516703, 3929, 4570, 4892…</code></pre>
</div>
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>nov2021 <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/aspatial/Data Vaksinasi Berbasis Kelurahan (30 November 2021).xlsx"</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(nov2021)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 268
Columns: 27
$ `KODE KELURAHAN`                             &lt;chr&gt; NA, "3172051003", "317304…
$ `WILAYAH KOTA`                               &lt;chr&gt; NA, "JAKARTA UTARA", "JAK…
$ KECAMATAN                                    &lt;chr&gt; NA, "PADEMANGAN", "TAMBOR…
$ KELURAHAN                                    &lt;chr&gt; "TOTAL", "ANCOL", "ANGKE"…
$ SASARAN                                      &lt;dbl&gt; 8941211, 23947, 29381, 29…
$ `BELUM VAKSIN`                               &lt;dbl&gt; 1723821, 5527, 5986, 6802…
$ `JUMLAH\r\nDOSIS 1`                          &lt;dbl&gt; 7217390, 18420, 23395, 22…
$ `JUMLAH\r\nDOSIS 2`                          &lt;dbl&gt; 6172636, 15466, 19404, 18…
$ `TOTAL VAKSIN\r\nDIBERIKAN`                  &lt;dbl&gt; 13390026, 33886, 42799, 4…
$ `LANSIA\r\nDOSIS 1`                          &lt;dbl&gt; 624751, 1473, 2391, 1385,…
$ `LANSIA\r\nDOSIS 2`                          &lt;dbl&gt; 571830, 1351, 2192, 1224,…
$ `LANSIA TOTAL \r\nVAKSIN DIBERIKAN`          &lt;dbl&gt; 1196581, 2824, 4583, 2609…
$ `PELAYAN PUBLIK\r\nDOSIS 1`                  &lt;dbl&gt; 1487961, 3980, 3926, 4614…
$ `PELAYAN PUBLIK\r\nDOSIS 2`                  &lt;dbl&gt; 1369705, 3601, 3516, 4146…
$ `PELAYAN PUBLIK TOTAL\r\nVAKSIN DIBERIKAN`   &lt;dbl&gt; 2857666, 7581, 7442, 8760…
$ `GOTONG ROYONG\r\nDOSIS 1`                   &lt;dbl&gt; 86710, 169, 176, 259, 101…
$ `GOTONG ROYONG\r\nDOSIS 2`                   &lt;dbl&gt; 83506, 163, 172, 252, 98,…
$ `GOTONG ROYONG TOTAL\r\nVAKSIN DIBERIKAN`    &lt;dbl&gt; 170216, 332, 348, 511, 19…
$ `TENAGA KESEHATAN\r\nDOSIS 1`                &lt;dbl&gt; 114292, 140, 135, 341, 12…
$ `TENAGA KESEHATAN\r\nDOSIS 2`                &lt;dbl&gt; 109221, 128, 128, 323, 12…
$ `TENAGA KESEHATAN TOTAL\r\nVAKSIN DIBERIKAN` &lt;dbl&gt; 223513, 268, 263, 664, 24…
$ `TAHAPAN 3\r\nDOSIS 1`                       &lt;dbl&gt; 4069550, 10473, 14182, 12…
$ `TAHAPAN 3\r\nDOSIS 2`                       &lt;dbl&gt; 3304266, 8329, 11215, 978…
$ `TAHAPAN 3 TOTAL\r\nVAKSIN DIBERIKAN`        &lt;dbl&gt; 7373816, 18802, 25397, 22…
$ `REMAJA\r\nDOSIS 1`                          &lt;dbl&gt; 834126, 2185, 2585, 2733,…
$ `REMAJA\r\nDOSIS 2`                          &lt;dbl&gt; 734108, 1894, 2181, 2355,…
$ `REMAJA TOTAL\r\nVAKSIN DIBERIKAN`           &lt;dbl&gt; 1568234, 4079, 4766, 5088…</code></pre>
</div>
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>dec2021 <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/aspatial/Data Vaksinasi Berbasis Kelurahan (31 Desember 2021).xlsx"</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(dec2021)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 268
Columns: 27
$ `KODE KELURAHAN`                             &lt;chr&gt; NA, "3172051003", "317304…
$ `WILAYAH KOTA`                               &lt;chr&gt; NA, "JAKARTA UTARA", "JAK…
$ KECAMATAN                                    &lt;chr&gt; NA, "PADEMANGAN", "TAMBOR…
$ KELURAHAN                                    &lt;chr&gt; "TOTAL", "ANCOL", "ANGKE"…
$ SASARAN                                      &lt;dbl&gt; 8941211, 23947, 29381, 29…
$ `BELUM VAKSIN`                               &lt;dbl&gt; 1623736, 5062, 5626, 6335…
$ `JUMLAH\r\nDOSIS 1`                          &lt;dbl&gt; 7317475, 18885, 23755, 22…
$ `JUMLAH\r\nDOSIS 2`                          &lt;dbl&gt; 6370175, 15996, 20026, 18…
$ `TOTAL VAKSIN\r\nDIBERIKAN`                  &lt;dbl&gt; 13687650, 34881, 43781, 4…
$ `LANSIA\r\nDOSIS 1`                          &lt;dbl&gt; 634516, 1520, 2427, 1418,…
$ `LANSIA\r\nDOSIS 2`                          &lt;dbl&gt; 586624, 1375, 2247, 1294,…
$ `LANSIA TOTAL \r\nVAKSIN DIBERIKAN`          &lt;dbl&gt; 1221140, 2895, 4674, 2712…
$ `PELAYAN PUBLIK\r\nDOSIS 1`                  &lt;dbl&gt; 1485857, 3981, 3922, 4603…
$ `PELAYAN PUBLIK\r\nDOSIS 2`                  &lt;dbl&gt; 1372180, 3607, 3521, 4153…
$ `PELAYAN PUBLIK TOTAL\r\nVAKSIN DIBERIKAN`   &lt;dbl&gt; 2858037, 7588, 7443, 8756…
$ `GOTONG ROYONG\r\nDOSIS 1`                   &lt;dbl&gt; 86905, 169, 176, 260, 101…
$ `GOTONG ROYONG\r\nDOSIS 2`                   &lt;dbl&gt; 83995, 164, 174, 253, 99,…
$ `GOTONG ROYONG TOTAL\r\nVAKSIN DIBERIKAN`    &lt;dbl&gt; 170900, 333, 350, 513, 20…
$ `TENAGA KESEHATAN\r\nDOSIS 1`                &lt;dbl&gt; 114612, 140, 136, 345, 12…
$ `TENAGA KESEHATAN\r\nDOSIS 2`                &lt;dbl&gt; 110119, 128, 129, 327, 12…
$ `TENAGA KESEHATAN TOTAL\r\nVAKSIN DIBERIKAN` &lt;dbl&gt; 224731, 268, 265, 672, 24…
$ `TAHAPAN 3\r\nDOSIS 1`                       &lt;dbl&gt; 4150113, 10841, 14450, 13…
$ `TAHAPAN 3\r\nDOSIS 2`                       &lt;dbl&gt; 3467714, 8782, 11715, 104…
$ `TAHAPAN 3 TOTAL\r\nVAKSIN DIBERIKAN`        &lt;dbl&gt; 7617827, 19623, 26165, 23…
$ `REMAJA\r\nDOSIS 1`                          &lt;dbl&gt; 845472, 2234, 2644, 2783,…
$ `REMAJA\r\nDOSIS 2`                          &lt;dbl&gt; 749543, 1940, 2240, 2401,…
$ `REMAJA TOTAL\r\nVAKSIN DIBERIKAN`           &lt;dbl&gt; 1595015, 4174, 4884, 5184…</code></pre>
</div>
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>jan2022 <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/aspatial/Data Vaksinasi Berbasis Kelurahan (31 Januari 2022).xlsx"</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(jan2022)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 268
Columns: 27
$ `KODE KELURAHAN`                             &lt;chr&gt; NA, "3172051003", "317304…
$ `WILAYAH KOTA`                               &lt;chr&gt; NA, "JAKARTA UTARA", "JAK…
$ KECAMATAN                                    &lt;chr&gt; NA, "PADEMANGAN", "TAMBOR…
$ KELURAHAN                                    &lt;chr&gt; "TOTAL", "ANCOL", "ANGKE"…
$ SASARAN                                      &lt;dbl&gt; 8941211, 23947, 29381, 29…
$ `BELUM VAKSIN`                               &lt;dbl&gt; 1538221, 4647, 5388, 5967…
$ `JUMLAH\r\nDOSIS 1`                          &lt;dbl&gt; 7402990, 19300, 23993, 23…
$ `JUMLAH\r\nDOSIS 2`                          &lt;dbl&gt; 6516678, 16477, 20463, 19…
$ `TOTAL VAKSIN\r\nDIBERIKAN`                  &lt;dbl&gt; 13919668, 35777, 44456, 4…
$ `LANSIA\r\nDOSIS 1`                          &lt;dbl&gt; 644280, 1564, 2459, 1446,…
$ `LANSIA\r\nDOSIS 2`                          &lt;dbl&gt; 598309, 1399, 2291, 1327,…
$ `LANSIA TOTAL \r\nVAKSIN DIBERIKAN`          &lt;dbl&gt; 1242589, 2963, 4750, 2773…
$ `PELAYAN PUBLIK\r\nDOSIS 1`                  &lt;dbl&gt; 1478564, 3971, 3900, 4592…
$ `PELAYAN PUBLIK\r\nDOSIS 2`                  &lt;dbl&gt; 1369268, 3604, 3506, 4158…
$ `PELAYAN PUBLIK TOTAL\r\nVAKSIN DIBERIKAN`   &lt;dbl&gt; 2847832, 7575, 7406, 8750…
$ `GOTONG ROYONG\r\nDOSIS 1`                   &lt;dbl&gt; 88073, 177, 178, 262, 102…
$ `GOTONG ROYONG\r\nDOSIS 2`                   &lt;dbl&gt; 85942, 171, 179, 260, 99,…
$ `GOTONG ROYONG TOTAL\r\nVAKSIN DIBERIKAN`    &lt;dbl&gt; 174015, 348, 357, 522, 20…
$ `TENAGA KESEHATAN\r\nDOSIS 1`                &lt;dbl&gt; 115123, 140, 135, 348, 12…
$ `TENAGA KESEHATAN\r\nDOSIS 2`                &lt;dbl&gt; 111364, 130, 130, 331, 12…
$ `TENAGA KESEHATAN TOTAL\r\nVAKSIN DIBERIKAN` &lt;dbl&gt; 226487, 270, 265, 679, 24…
$ `TAHAPAN 3\r\nDOSIS 1`                       &lt;dbl&gt; 4215232, 11158, 14620, 13…
$ `TAHAPAN 3\r\nDOSIS 2`                       &lt;dbl&gt; 3579348, 9173, 12024, 109…
$ `TAHAPAN 3 TOTAL\r\nVAKSIN DIBERIKAN`        &lt;dbl&gt; 7794580, 20331, 26644, 24…
$ `REMAJA\r\nDOSIS 1`                          &lt;dbl&gt; 861718, 2290, 2701, 2840,…
$ `REMAJA\r\nDOSIS 2`                          &lt;dbl&gt; 772447, 2000, 2333, 2488,…
$ `REMAJA TOTAL\r\nVAKSIN DIBERIKAN`           &lt;dbl&gt; 1634165, 4290, 5034, 5328…</code></pre>
</div>
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>feb2022 <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/aspatial/Data Vaksinasi Berbasis Kelurahan (27 Februari 2022).xlsx"</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(feb2022)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 268
Columns: 27
$ `KODE KELURAHAN`                             &lt;chr&gt; NA, "3172051003", "317304…
$ `WILAYAH KOTA`                               &lt;chr&gt; NA, "JAKARTA UTARA", "JAK…
$ KECAMATAN                                    &lt;chr&gt; NA, "PADEMANGAN", "TAMBOR…
$ KELURAHAN                                    &lt;chr&gt; "TOTAL", "ANCOL", "ANGKE"…
$ SASARAN                                      &lt;dbl&gt; 8941211, 23947, 29381, 29…
$ `BELUM VAKSIN`                               &lt;dbl&gt; 1517196, 4592, 5319, 5903…
$ `JUMLAH\r\nDOSIS 1`                          &lt;dbl&gt; 7424015, 19355, 24062, 23…
$ `JUMLAH\r\nDOSIS 2`                          &lt;dbl&gt; 6590380, 16687, 20738, 19…
$ `TOTAL VAKSIN\r\nDIBERIKAN`                  &lt;dbl&gt; 14014395, 36042, 44800, 4…
$ `LANSIA\r\nDOSIS 1`                          &lt;dbl&gt; 646481, 1567, 2465, 1451,…
$ `LANSIA\r\nDOSIS 2`                          &lt;dbl&gt; 604751, 1418, 2336, 1348,…
$ `LANSIA TOTAL \r\nVAKSIN DIBERIKAN`          &lt;dbl&gt; 1251232, 2985, 4801, 2799…
$ `PELAYAN PUBLIK\r\nDOSIS 1`                  &lt;dbl&gt; 1478545, 3971, 3899, 4590…
$ `PELAYAN PUBLIK\r\nDOSIS 2`                  &lt;dbl&gt; 1371190, 3614, 3512, 4161…
$ `PELAYAN PUBLIK TOTAL\r\nVAKSIN DIBERIKAN`   &lt;dbl&gt; 2849735, 7585, 7411, 8751…
$ `GOTONG ROYONG\r\nDOSIS 1`                   &lt;dbl&gt; 88088, 178, 178, 262, 102…
$ `GOTONG ROYONG\r\nDOSIS 2`                   &lt;dbl&gt; 86046, 171, 179, 260, 99,…
$ `GOTONG ROYONG TOTAL\r\nVAKSIN DIBERIKAN`    &lt;dbl&gt; 174134, 349, 357, 522, 20…
$ `TENAGA KESEHATAN\r\nDOSIS 1`                &lt;dbl&gt; 115186, 140, 135, 348, 12…
$ `TENAGA KESEHATAN\r\nDOSIS 2`                &lt;dbl&gt; 111623, 130, 130, 331, 12…
$ `TENAGA KESEHATAN TOTAL\r\nVAKSIN DIBERIKAN` &lt;dbl&gt; 226809, 270, 265, 679, 24…
$ `TAHAPAN 3\r\nDOSIS 1`                       &lt;dbl&gt; 4232389, 11200, 14670, 13…
$ `TAHAPAN 3\r\nDOSIS 2`                       &lt;dbl&gt; 3638187, 9327, 12227, 111…
$ `TAHAPAN 3 TOTAL\r\nVAKSIN DIBERIKAN`        &lt;dbl&gt; 7870576, 20527, 26897, 24…
$ `REMAJA\r\nDOSIS 1`                          &lt;dbl&gt; 863326, 2299, 2715, 2845,…
$ `REMAJA\r\nDOSIS 2`                          &lt;dbl&gt; 778583, 2027, 2354, 2512,…
$ `REMAJA TOTAL\r\nVAKSIN DIBERIKAN`           &lt;dbl&gt; 1641909, 4326, 5069, 5357…</code></pre>
</div>
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>mar2022 <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/aspatial/Data Vaksinasi Berbasis Kelurahan (31 Maret 2022).xlsx"</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(mar2022)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 268
Columns: 34
$ `KODE KELURAHAN`                             &lt;chr&gt; NA, "3172051003", "317304…
$ `WILAYAH KOTA`                               &lt;chr&gt; NA, "JAKARTA UTARA", "JAK…
$ KECAMATAN                                    &lt;chr&gt; NA, "PADEMANGAN", "TAMBOR…
$ KELURAHAN                                    &lt;chr&gt; "TOTAL", "ANCOL", "ANGKE"…
$ SASARAN                                      &lt;dbl&gt; 8941211, 23947, 29381, 29…
$ `BELUM VAKSIN`                               &lt;dbl&gt; 1482471, 4522, 5186, 5780…
$ `JUMLAH\r\nDOSIS 1`                          &lt;dbl&gt; 7458740, 19425, 24195, 23…
$ `JUMLAH\r\nDOSIS 2`                          &lt;dbl&gt; 6682911, 16909, 21000, 20…
$ `JUMLAH\r\nDOSIS 3`                          &lt;dbl&gt; 1836511, 3934, 6122, 4124…
$ `TOTAL VAKSIN\r\nDIBERIKAN`                  &lt;dbl&gt; 15978162, 40268, 51317, 4…
$ `LANSIA\r\nDOSIS 1`                          &lt;dbl&gt; 649601, 1574, 2475, 1457,…
$ `LANSIA\r\nDOSIS 2`                          &lt;dbl&gt; 610754, 1433, 2350, 1366,…
$ `LANSIA\r\nDOSIS 3`                          &lt;dbl&gt; 610754, 1433, 2350, 1366,…
$ `LANSIA TOTAL \r\nVAKSIN DIBERIKAN`          &lt;dbl&gt; 1533150, 3545, 6052, 3283…
$ `PELAYAN PUBLIK\r\nDOSIS 1`                  &lt;dbl&gt; 1481237, 3980, 3910, 4604…
$ `PELAYAN PUBLIK\r\nDOSIS 2`                  &lt;dbl&gt; 1375686, 3634, 3523, 4175…
$ `PELAYAN PUBLIK\r\nDOSIS 3`                  &lt;dbl&gt; 200536, 579, 660, 453, 24…
$ `PELAYAN PUBLIK TOTAL\r\nVAKSIN DIBERIKAN`   &lt;dbl&gt; 3057459, 8193, 8093, 9232…
$ `GOTONG ROYONG\r\nDOSIS 1`                   &lt;dbl&gt; 88150, 178, 178, 262, 102…
$ `GOTONG ROYONG\r\nDOSIS 2`                   &lt;dbl&gt; 86122, 173, 179, 260, 99,…
$ `GOTONG ROYONG\r\nDOSIS 3`                   &lt;dbl&gt; 19460, 22, 53, 57, 19, 41…
$ `GOTONG ROYONG TOTAL\r\nVAKSIN DIBERIKAN`    &lt;dbl&gt; 193732, 373, 410, 579, 22…
$ `TENAGA KESEHATAN\r\nDOSIS 1`                &lt;dbl&gt; 115527, 140, 135, 348, 12…
$ `TENAGA KESEHATAN\r\nDOSIS 2`                &lt;dbl&gt; 112027, 130, 130, 331, 12…
$ `TENAGA KESEHATAN\r\nDOSIS 3`                &lt;dbl&gt; 84640, 103, 94, 239, 83, …
$ `TENAGA KESEHATAN TOTAL\r\nVAKSIN DIBERIKAN` &lt;dbl&gt; 312194, 373, 359, 918, 32…
$ `TAHAPAN 3\r\nDOSIS 1`                       &lt;dbl&gt; 4258776, 11250, 14773, 13…
$ `TAHAPAN 3\r\nDOSIS 2`                       &lt;dbl&gt; 3715052, 9502, 12436, 114…
$ `TAHAPAN 3\r\nDOSIS 3`                       &lt;dbl&gt; 1248211, 2671, 4048, 2891…
$ `TAHAPAN 3 TOTAL\r\nVAKSIN DIBERIKAN`        &lt;dbl&gt; 9222039, 23423, 31257, 28…
$ `REMAJA\r\nDOSIS 1`                          &lt;dbl&gt; 865449, 2303, 2724, 2851,…
$ `REMAJA\r\nDOSIS 2`                          &lt;dbl&gt; 783270, 2037, 2382, 2541,…
$ `REMAJA\r\nDOSIS 3`                          &lt;dbl&gt; 10869, 21, 40, 24, 7, 28,…
$ `REMAJA TOTAL\r\nVAKSIN DIBERIKAN`           &lt;dbl&gt; 1659588, 4361, 5146, 5416…</code></pre>
</div>
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>apr2022 <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/aspatial/Data Vaksinasi Berbasis Kelurahan (30 April 2022).xlsx"</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(apr2022)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 268
Columns: 34
$ `KODE KELURAHAN`                             &lt;chr&gt; NA, "3172051003", "317304…
$ `WILAYAH KOTA`                               &lt;chr&gt; NA, "JAKARTA UTARA", "JAK…
$ KECAMATAN                                    &lt;chr&gt; NA, "PADEMANGAN", "TAMBOR…
$ KELURAHAN                                    &lt;chr&gt; "TOTAL", "ANCOL", "ANGKE"…
$ SASARAN                                      &lt;dbl&gt; 8941211, 23947, 29381, 29…
$ `BELUM VAKSIN`                               &lt;dbl&gt; 1453423, 4449, 5101, 5699…
$ `JUMLAH\r\nDOSIS 1`                          &lt;dbl&gt; 7487788, 19498, 24280, 23…
$ `JUMLAH\r\nDOSIS 2`                          &lt;dbl&gt; 6727002, 17027, 21134, 20…
$ `JUMLAH\r\nDOSIS 3`                          &lt;dbl&gt; 2720796, 6568, 8915, 6491…
$ `TOTAL VAKSIN\r\nDIBERIKAN`                  &lt;dbl&gt; 16935586, 43093, 54329, 5…
$ `LANSIA\r\nDOSIS 1`                          &lt;dbl&gt; 651696, 1579, 2481, 1458,…
$ `LANSIA\r\nDOSIS 2`                          &lt;dbl&gt; 613044, 1441, 2360, 1376,…
$ `LANSIA\r\nDOSIS 3`                          &lt;dbl&gt; 613044, 1441, 2360, 1376,…
$ `LANSIA TOTAL \r\nVAKSIN DIBERIKAN`          &lt;dbl&gt; 1599248, 3750, 6301, 3425…
$ `PELAYAN PUBLIK\r\nDOSIS 1`                  &lt;dbl&gt; 1483630, 3983, 3920, 4611…
$ `PELAYAN PUBLIK\r\nDOSIS 2`                  &lt;dbl&gt; 1378338, 3640, 3529, 4187…
$ `PELAYAN PUBLIK\r\nDOSIS 3`                  &lt;dbl&gt; 366145, 1099, 1096, 941, …
$ `PELAYAN PUBLIK TOTAL\r\nVAKSIN DIBERIKAN`   &lt;dbl&gt; 3228113, 8722, 8545, 9739…
$ `GOTONG ROYONG\r\nDOSIS 1`                   &lt;dbl&gt; 88200, 178, 178, 262, 102…
$ `GOTONG ROYONG\r\nDOSIS 2`                   &lt;dbl&gt; 86184, 173, 179, 260, 99,…
$ `GOTONG ROYONG\r\nDOSIS 3`                   &lt;dbl&gt; 38179, 71, 95, 120, 41, 7…
$ `GOTONG ROYONG TOTAL\r\nVAKSIN DIBERIKAN`    &lt;dbl&gt; 212563, 422, 452, 642, 24…
$ `TENAGA KESEHATAN\r\nDOSIS 1`                &lt;dbl&gt; 115623, 140, 135, 348, 12…
$ `TENAGA KESEHATAN\r\nDOSIS 2`                &lt;dbl&gt; 112253, 130, 130, 333, 12…
$ `TENAGA KESEHATAN\r\nDOSIS 3`                &lt;dbl&gt; 89811, 109, 105, 259, 91,…
$ `TENAGA KESEHATAN TOTAL\r\nVAKSIN DIBERIKAN` &lt;dbl&gt; 317687, 379, 370, 940, 33…
$ `TAHAPAN 3\r\nDOSIS 1`                       &lt;dbl&gt; 4281576, 11308, 14842, 13…
$ `TAHAPAN 3\r\nDOSIS 2`                       &lt;dbl&gt; 3750893, 9596, 12545, 116…
$ `TAHAPAN 3\r\nDOSIS 3`                       &lt;dbl&gt; 1866526, 4503, 6084, 4519…
$ `TAHAPAN 3 TOTAL\r\nVAKSIN DIBERIKAN`        &lt;dbl&gt; 9898995, 25407, 33471, 29…
$ `REMAJA\r\nDOSIS 1`                          &lt;dbl&gt; 867063, 2310, 2724, 2858,…
$ `REMAJA\r\nDOSIS 2`                          &lt;dbl&gt; 786290, 2047, 2391, 2557,…
$ `REMAJA\r\nDOSIS 3`                          &lt;dbl&gt; 25627, 56, 75, 61, 19, 71…
$ `REMAJA TOTAL\r\nVAKSIN DIBERIKAN`           &lt;dbl&gt; 1678980, 4413, 5190, 5476…</code></pre>
</div>
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>may2022 <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/aspatial/Data Vaksinasi Berbasis Kelurahan (31 Mei 2022).xlsx"</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(may2022)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 268
Columns: 34
$ `KODE KELURAHAN`                             &lt;chr&gt; NA, "3172051003", "317304…
$ `WILAYAH KOTA`                               &lt;chr&gt; NA, "JAKARTA UTARA", "JAK…
$ KECAMATAN                                    &lt;chr&gt; NA, "PADEMANGAN", "TAMBOR…
$ KELURAHAN                                    &lt;chr&gt; "TOTAL", "ANCOL", "ANGKE"…
$ SASARAN                                      &lt;dbl&gt; 8941211, 23947, 29381, 29…
$ `BELUM VAKSIN`                               &lt;dbl&gt; 1445540, 4440, 5084, 5676…
$ `JUMLAH\r\nDOSIS 1`                          &lt;dbl&gt; 7495671, 19507, 24297, 23…
$ `JUMLAH\r\nDOSIS 2`                          &lt;dbl&gt; 6743764, 17077, 21182, 20…
$ `JUMLAH\r\nDOSIS 3`                          &lt;dbl&gt; 2885301, 7022, 9484, 7030…
$ `TOTAL VAKSIN\r\nDIBERIKAN`                  &lt;dbl&gt; 17124736, 43606, 54963, 5…
$ `LANSIA\r\nDOSIS 1`                          &lt;dbl&gt; 652411, 1580, 2482, 1461,…
$ `LANSIA\r\nDOSIS 2`                          &lt;dbl&gt; 614259, 1442, 2367, 1378,…
$ `LANSIA\r\nDOSIS 3`                          &lt;dbl&gt; 614259, 1442, 2367, 1378,…
$ `LANSIA TOTAL \r\nVAKSIN DIBERIKAN`          &lt;dbl&gt; 1615382, 3804, 6385, 3468…
$ `PELAYAN PUBLIK\r\nDOSIS 1`                  &lt;dbl&gt; 1483896, 3982, 3920, 4612…
$ `PELAYAN PUBLIK\r\nDOSIS 2`                  &lt;dbl&gt; 1379577, 3645, 3534, 4192…
$ `PELAYAN PUBLIK\r\nDOSIS 3`                  &lt;dbl&gt; 395504, 1185, 1185, 1033,…
$ `PELAYAN PUBLIK TOTAL\r\nVAKSIN DIBERIKAN`   &lt;dbl&gt; 3258977, 8812, 8639, 9837…
$ `GOTONG ROYONG\r\nDOSIS 1`                   &lt;dbl&gt; 88234, 179, 178, 262, 102…
$ `GOTONG ROYONG\r\nDOSIS 2`                   &lt;dbl&gt; 86232, 173, 179, 260, 99,…
$ `GOTONG ROYONG\r\nDOSIS 3`                   &lt;dbl&gt; 43402, 100, 111, 132, 53,…
$ `GOTONG ROYONG TOTAL\r\nVAKSIN DIBERIKAN`    &lt;dbl&gt; 217868, 452, 468, 654, 25…
$ `TENAGA KESEHATAN\r\nDOSIS 1`                &lt;dbl&gt; 115658, 140, 135, 348, 12…
$ `TENAGA KESEHATAN\r\nDOSIS 2`                &lt;dbl&gt; 112327, 130, 131, 333, 12…
$ `TENAGA KESEHATAN\r\nDOSIS 3`                &lt;dbl&gt; 91061, 110, 108, 262, 93,…
$ `TENAGA KESEHATAN TOTAL\r\nVAKSIN DIBERIKAN` &lt;dbl&gt; 319046, 380, 374, 943, 33…
$ `TAHAPAN 3\r\nDOSIS 1`                       &lt;dbl&gt; 4287820, 11318, 14850, 13…
$ `TAHAPAN 3\r\nDOSIS 2`                       &lt;dbl&gt; 3763773, 9632, 12577, 116…
$ `TAHAPAN 3\r\nDOSIS 3`                       &lt;dbl&gt; 1975879, 4777, 6455, 4893…
$ `TAHAPAN 3 TOTAL\r\nVAKSIN DIBERIKAN`        &lt;dbl&gt; 10027472, 25727, 33882, 3…
$ `REMAJA\r\nDOSIS 1`                          &lt;dbl&gt; 867652, 2308, 2732, 2858,…
$ `REMAJA\r\nDOSIS 2`                          &lt;dbl&gt; 787596, 2055, 2394, 2562,…
$ `REMAJA\r\nDOSIS 3`                          &lt;dbl&gt; 30743, 68, 89, 81, 26, 80…
$ `REMAJA TOTAL\r\nVAKSIN DIBERIKAN`           &lt;dbl&gt; 1685991, 4431, 5215, 5501…</code></pre>
</div>
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>jun2022 <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/aspatial/Data Vaksinasi Berbasis Kelurahan (30 Juni 2022).xlsx"</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(jun2022)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 268
Columns: 34
$ `KODE KELURAHAN`                             &lt;chr&gt; NA, "3172051003", "317304…
$ `WILAYAH KOTA`                               &lt;chr&gt; NA, "JAKARTA UTARA", "JAK…
$ KECAMATAN                                    &lt;chr&gt; NA, "PADEMANGAN", "TAMBOR…
$ KELURAHAN                                    &lt;chr&gt; "TOTAL", "ANCOL", "ANGKE"…
$ SASARAN                                      &lt;dbl&gt; 8941211, 23947, 29381, 29…
$ `BELUM VAKSIN`                               &lt;dbl&gt; 1431393, 4402, 5041, 5632…
$ `JUMLAH\r\nDOSIS 1`                          &lt;dbl&gt; 7509818, 19545, 24340, 23…
$ `JUMLAH\r\nDOSIS 2`                          &lt;dbl&gt; 6756584, 17106, 21213, 20…
$ `JUMLAH\r\nDOSIS 3`                          &lt;dbl&gt; 3031594, 7369, 10086, 739…
$ `TOTAL VAKSIN\r\nDIBERIKAN`                  &lt;dbl&gt; 17297996, 44020, 55639, 5…
$ `LANSIA\r\nDOSIS 1`                          &lt;dbl&gt; 653401, 1582, 2483, 1466,…
$ `LANSIA\r\nDOSIS 2`                          &lt;dbl&gt; 615341, 1447, 2368, 1382,…
$ `LANSIA\r\nDOSIS 3`                          &lt;dbl&gt; 615341, 1447, 2368, 1382,…
$ `LANSIA TOTAL \r\nVAKSIN DIBERIKAN`          &lt;dbl&gt; 1630553, 3848, 6464, 3495…
$ `PELAYAN PUBLIK\r\nDOSIS 1`                  &lt;dbl&gt; 1484892, 3982, 3924, 4613…
$ `PELAYAN PUBLIK\r\nDOSIS 2`                  &lt;dbl&gt; 1380501, 3646, 3536, 4195…
$ `PELAYAN PUBLIK\r\nDOSIS 3`                  &lt;dbl&gt; 420795, 1244, 1265, 1104,…
$ `PELAYAN PUBLIK TOTAL\r\nVAKSIN DIBERIKAN`   &lt;dbl&gt; 3286188, 8872, 8725, 9912…
$ `GOTONG ROYONG\r\nDOSIS 1`                   &lt;dbl&gt; 88277, 180, 178, 262, 102…
$ `GOTONG ROYONG\r\nDOSIS 2`                   &lt;dbl&gt; 86277, 174, 179, 260, 99,…
$ `GOTONG ROYONG\r\nDOSIS 3`                   &lt;dbl&gt; 45143, 104, 115, 135, 56,…
$ `GOTONG ROYONG TOTAL\r\nVAKSIN DIBERIKAN`    &lt;dbl&gt; 219697, 458, 472, 657, 25…
$ `TENAGA KESEHATAN\r\nDOSIS 1`                &lt;dbl&gt; 115697, 140, 135, 348, 12…
$ `TENAGA KESEHATAN\r\nDOSIS 2`                &lt;dbl&gt; 112383, 130, 131, 333, 12…
$ `TENAGA KESEHATAN\r\nDOSIS 3`                &lt;dbl&gt; 91999, 113, 108, 266, 95,…
$ `TENAGA KESEHATAN TOTAL\r\nVAKSIN DIBERIKAN` &lt;dbl&gt; 320079, 383, 374, 947, 33…
$ `TAHAPAN 3\r\nDOSIS 1`                       &lt;dbl&gt; 4298906, 11352, 14884, 13…
$ `TAHAPAN 3\r\nDOSIS 2`                       &lt;dbl&gt; 3773713, 9652, 12601, 116…
$ `TAHAPAN 3\r\nDOSIS 3`                       &lt;dbl&gt; 2075349, 5009, 6872, 5151…
$ `TAHAPAN 3 TOTAL\r\nVAKSIN DIBERIKAN`        &lt;dbl&gt; 10147968, 26013, 34357, 3…
$ `REMAJA\r\nDOSIS 1`                          &lt;dbl&gt; 868645, 2309, 2736, 2862,…
$ `REMAJA\r\nDOSIS 2`                          &lt;dbl&gt; 788369, 2057, 2398, 2564,…
$ `REMAJA\r\nDOSIS 3`                          &lt;dbl&gt; 36497, 80, 113, 95, 29, 1…
$ `REMAJA TOTAL\r\nVAKSIN DIBERIKAN`           &lt;dbl&gt; 1693511, 4446, 5247, 5521…</code></pre>
</div>
</div>
</section>
<section id="creating-an-aspatial-data-pre-processing-function" class="level3">
<h3 class="anchored" data-anchor-id="creating-an-aspatial-data-pre-processing-function">4.3.2 Creating an Aspatial Data Pre-processing Function</h3>
<p>Firstly, here are some requirements for our aspatial data: Columns of interest: - KODE KELURAHAN: sub-district code - KELURAHAN: sub-district - SASARAN: target - BELUM VAKSIN: not yet vaccinated - TOTAL VAKSIN DIBERIKAN: total vaccine administered</p>
<p>We need to create an extra Date column that has the month and year of the observation. Note that the files have a naming convention “Data Vaksinasi Berbasis Kelurahan (DD Month YYYY).xlsx”</p>
<div class="cell">
<details>
<summary>Show the code!</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># takes in an aspatial data filepath and returns a processed output</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>aspatial_preprocess <span class="ot">&lt;-</span> <span class="cf">function</span>(filepath){</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  result_file <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(filepath)[<span class="sc">-</span><span class="dv">1</span>,]</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create the Date Column</span></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># the format of our files is: Data Vaksinasi Berbasis Kelurahan (DD Month YYYY)</span></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># while the start is technically "(", "(" is part of a regular expression and leads to a warning message, so we'll use "Kelurahan" instead. The [[1]] refers to the first element in the list.</span></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># we're loading it as DD-Month-YYYY format</span></span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># the end is 1 space before "Pukul", which means we have to -2 spaces (one for P, one for space)</span></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># as such, the most relevant functions are substr (returns a substring) and either str_locate (returns location of substring as an integer matrix) or gregexpr (returns a list of locations of substring)</span></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># reference https://stackoverflow.com/questions/14249562/find-the-location-of-a-character-in-string</span></span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>  startpoint <span class="ot">&lt;-</span> <span class="fu">gregexpr</span>(<span class="at">pattern=</span><span class="st">"Kelurahan"</span>, filepath)[[<span class="dv">1</span>]] <span class="sc">+</span> <span class="dv">11</span></span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a>  result_file<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">substr</span>(filepath, startpoint, <span class="fu">nchar</span>(filepath)<span class="sc">-</span><span class="dv">6</span>)</span>
<span id="cb54-15"><a href="#cb54-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb54-16"><a href="#cb54-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create total population (vaccinated and non-vaccinated)</span></span>
<span id="cb54-17"><a href="#cb54-17" aria-hidden="true" tabindex="-1"></a>  result_file<span class="sc">$</span>TotalPop <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(result_file[, <span class="fu">c</span>(<span class="st">"BELUM VAKSIN"</span>, <span class="st">"TOTAL VAKSIN</span><span class="sc">\r\n</span><span class="st">DIBERIKAN"</span>)])</span>
<span id="cb54-18"><a href="#cb54-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb54-19"><a href="#cb54-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Retain the Relevant Columns</span></span>
<span id="cb54-20"><a href="#cb54-20" aria-hidden="true" tabindex="-1"></a>  result_file <span class="ot">&lt;-</span> result_file <span class="sc">%&gt;%</span> </span>
<span id="cb54-21"><a href="#cb54-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="st">"Date"</span>, </span>
<span id="cb54-22"><a href="#cb54-22" aria-hidden="true" tabindex="-1"></a>           <span class="st">"KODE KELURAHAN"</span>, </span>
<span id="cb54-23"><a href="#cb54-23" aria-hidden="true" tabindex="-1"></a>           <span class="st">"KELURAHAN"</span>, </span>
<span id="cb54-24"><a href="#cb54-24" aria-hidden="true" tabindex="-1"></a>           <span class="st">"SASARAN"</span>, </span>
<span id="cb54-25"><a href="#cb54-25" aria-hidden="true" tabindex="-1"></a>           <span class="st">"BELUM VAKSIN"</span>, </span>
<span id="cb54-26"><a href="#cb54-26" aria-hidden="true" tabindex="-1"></a>           <span class="st">"TOTAL VAKSIN</span><span class="sc">\r\n</span><span class="st">DIBERIKAN"</span>, </span>
<span id="cb54-27"><a href="#cb54-27" aria-hidden="true" tabindex="-1"></a>           <span class="st">"TotalPop"</span>)</span>
<span id="cb54-28"><a href="#cb54-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(result_file)</span>
<span id="cb54-29"><a href="#cb54-29" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># in the folder 'data/aspatial', find files with the extension '.xlsx' and add it to our fileslist </span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the full.names=TRUE prepends the directory path to the file names, giving a relative file path - otherwise, only the file names (not the paths) would be returned </span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="co"># reference: https://stat.ethz.ch/R-manual/R-devel/library/base/html/list.files.html</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>fileslist <span class="ot">&lt;-</span><span class="fu">list.files</span>(<span class="at">path =</span> <span class="st">"data/aspatial"</span>, <span class="at">pattern =</span> <span class="st">"*.xlsx"</span>, <span class="at">full.names=</span><span class="cn">TRUE</span>)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="co"># afterwards, for every element in fileslist, apply aspatial_process function</span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>dflist <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">seq_along</span>(fileslist), <span class="cf">function</span>(x) <span class="fu">aspatial_preprocess</span>(fileslist[x]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>vacc_jakarta <span class="ot">&lt;-</span> <span class="fu">ldply</span>(dflist, data.frame)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(vacc_jakarta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,204
Columns: 7
$ Date                    &lt;chr&gt; "27 Februari 2022", "27 Februari 2022", "27 Fe…
$ KODE.KELURAHAN          &lt;chr&gt; "3172051003", "3173041007", "3175041005", "317…
$ KELURAHAN               &lt;chr&gt; "ANCOL", "ANGKE", "BALE KAMBANG", "BALI MESTER…
$ SASARAN                 &lt;dbl&gt; 23947, 29381, 29074, 9752, 26285, 21566, 23886…
$ BELUM.VAKSIN            &lt;dbl&gt; 4592, 5319, 5903, 1649, 4030, 3950, 3344, 9382…
$ TOTAL.VAKSIN..DIBERIKAN &lt;dbl&gt; 36042, 44800, 42925, 15348, 42415, 33278, 3929…
$ TotalPop                &lt;dbl&gt; 40634, 50119, 48828, 16997, 46445, 37228, 4264…</code></pre>
</div>
</div>
</section>
<section id="importing-the-aspatial-data" class="level3">
<h3 class="anchored" data-anchor-id="importing-the-aspatial-data">Importing the Aspatial Data</h3>
</section>
</section>
<section id="choropleth-mapping-and-analysis" class="level2">
<h2 class="anchored" data-anchor-id="choropleth-mapping-and-analysis">4.3 Choropleth Mapping and Analysis</h2>
</section>
<section id="local-gi-analysis" class="level2">
<h2 class="anchored" data-anchor-id="local-gi-analysis">4.4 Local Gi* Analysis</h2>
</section>
<section id="emerging-hot-spot-analysis-ehsa" class="level2">
<h2 class="anchored" data-anchor-id="emerging-hot-spot-analysis-ehsa">4.5 Emerging Hot Spot Analysis (EHSA)</h2>
</section>
</section>
<section id="references" class="level1">
<h1>5 References</h1>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>